
set_property PACKAGE_PIN AK34 [get_ports USRCLK_P]
set_property IOSTANDARD LVDS [get_ports USRCLK_P]
set_property PACKAGE_PIN AL34 [get_ports USRCLK_N]
set_property IOSTANDARD LVDS [get_ports USRCLK_N]

set_property PACKAGE_PIN AV39 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property PACKAGE_PIN AR40 [get_ports req]
set_property IOSTANDARD LVCMOS18 [get_ports req]
set_property PACKAGE_PIN AP40 [get_ports we]
set_property IOSTANDARD LVCMOS18 [get_ports we]

## exp_fix only
# set_property PACKAGE_PIN AN31 [get_ports sel]
# set_property IOSTANDARD LVCMOS18 [get_ports sel]
# set_property PACKAGE_PIN AU38 [get_ports re]
# set_property IOSTANDARD LVCMOS18 [get_ports re]

# For both modules
set_property PACKAGE_PIN AW40 [get_ports tn[0]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[0]]
set_property PACKAGE_PIN AV30 [get_ports tn[1]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[1]]
set_property PACKAGE_PIN AY33 [get_ports tn[2]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[2]]
set_property PACKAGE_PIN BA31 [get_ports tn[3]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[3]]
set_property PACKAGE_PIN BA32 [get_ports tn[4]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[4]]
set_property PACKAGE_PIN AW30 [get_ports tn[5]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[5]]
set_property PACKAGE_PIN AY30 [get_ports tn[6]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[6]]
set_property PACKAGE_PIN BA30 [get_ports tn[7]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[7]]
set_property PACKAGE_PIN BB31 [get_ports tn[8]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[8]]
set_property PACKAGE_PIN AT31 [get_ports tn[9]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[9]]
set_property PACKAGE_PIN AW31 [get_ports tn[10]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[10]]
set_property PACKAGE_PIN AR33 [get_ports tn[11]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[11]]
# exp_fix bin = 6->8
set_property PACKAGE_PIN AW36 [get_ports tn[12]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[12]]
set_property PACKAGE_PIN BA34 [get_ports tn[13]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[13]]
set_property PACKAGE_PIN BB34 [get_ports tn[14]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[14]]
set_property PACKAGE_PIN BA36 [get_ports tn[15]]
set_property IOSTANDARD LVCMOS18 [get_ports tn[15]]

# For both modules
set_property PACKAGE_PIN AM39 [get_ports data_out[0]] 
set_property IOSTANDARD LVCMOS18 [get_ports data_out[0]]
set_property PACKAGE_PIN AN39 [get_ports data_out[1]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[1]]
set_property PACKAGE_PIN AR37 [get_ports data_out[2]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[2]]
set_property PACKAGE_PIN AT37 [get_ports data_out[3]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[3]]
set_property PACKAGE_PIN AR35 [get_ports data_out[4]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[4]]
set_property PACKAGE_PIN AP41 [get_ports data_out[5]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[5]]
set_property PACKAGE_PIN AP42 [get_ports data_out[6]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[6]]
set_property PACKAGE_PIN AU39 [get_ports data_out[7]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[7]]
set_property PACKAGE_PIN AG31 [get_ports data_out[8]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[8]]
set_property PACKAGE_PIN AF30 [get_ports data_out[9]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[9]]
set_property PACKAGE_PIN AK29 [get_ports data_out[10]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[10]]
set_property PACKAGE_PIN AK28 [get_ports data_out[11]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[11]]
# exp_fix only
set_property PACKAGE_PIN AG29 [get_ports data_out[12]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[12]]
set_property PACKAGE_PIN AK30 [get_ports data_out[13]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[13]]
set_property PACKAGE_PIN AJ30 [get_ports data_out[14]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[14]]
set_property PACKAGE_PIN AH30 [get_ports data_out[15]]
set_property IOSTANDARD LVCMOS18 [get_ports data_out[15]]


# For both modules
set_property PACKAGE_PIN AH29 [get_ports data_in[0]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[0]]
set_property PACKAGE_PIN AL30 [get_ports data_in[1]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[1]]
set_property PACKAGE_PIN AL29 [get_ports data_in[2]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[2]]
set_property PACKAGE_PIN AN33 [get_ports data_in[3]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[3]]
set_property PACKAGE_PIN AM33 [get_ports data_in[4]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[4]]
set_property PACKAGE_PIN AM32 [get_ports data_in[5]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[5]]
set_property PACKAGE_PIN AV41 [get_ports data_in[6]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[6]]
set_property PACKAGE_PIN AU41 [get_ports data_in[7]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[7]]
set_property PACKAGE_PIN BA42 [get_ports data_in[8]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[8]]
set_property PACKAGE_PIN AU42 [get_ports data_in[9]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[9]]
set_property PACKAGE_PIN AT41 [get_ports data_in[10]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[10]]
set_property PACKAGE_PIN BA40 [get_ports data_in[11]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[11]]
# exp_fix only
set_property PACKAGE_PIN BA39 [get_ports data_in[12]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[12]]
set_property PACKAGE_PIN BB39 [get_ports data_in[13]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[13]]
set_property PACKAGE_PIN AW42 [get_ports data_in[14]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[14]]
set_property PACKAGE_PIN AW41 [get_ports data_in[15]]
set_property IOSTANDARD LVCMOS18 [get_ports data_in[15]]


# For both module
set_property PACKAGE_PIN AM36 [get_ports addr_in[0]]
set_property IOSTANDARD LVCMOS18 [get_ports addr_in[0]]
set_property PACKAGE_PIN AN36 [get_ports addr_in[1]]
set_property IOSTANDARD LVCMOS18 [get_ports addr_in[1]]
set_property PACKAGE_PIN AJ36 [get_ports addr_in[2]]
set_property IOSTANDARD LVCMOS18 [get_ports addr_in[2]]
set_property PACKAGE_PIN AJ37 [get_ports addr_in[3]]
set_property IOSTANDARD LVCMOS18 [get_ports addr_in[3]]
set_property PACKAGE_PIN AK37 [get_ports addr_in[4]]
set_property IOSTANDARD LVCMOS18 [get_ports addr_in[4]]
set_property PACKAGE_PIN AL37 [get_ports addr_in[5]]
set_property IOSTANDARD LVCMOS18 [get_ports addr_in[5]]
# exp_fix bin = 6->8
set_property PACKAGE_PIN AT34 [get_ports addr_in[6]]
set_property IOSTANDARD LVCMOS18 [get_ports addr_in[6]]
set_property PACKAGE_PIN AY35 [get_ports addr_in[7]]
set_property IOSTANDARD LVCMOS18 [get_ports addr_in[7]]


# For both module
set_property PACKAGE_PIN AN35 [get_ports result_out[0]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[0]]
set_property PACKAGE_PIN AP35 [get_ports result_out[1]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[1]]
set_property PACKAGE_PIN AM37 [get_ports result_out[2]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[2]]
set_property PACKAGE_PIN AG33 [get_ports result_out[3]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[3]]
set_property PACKAGE_PIN AH33 [get_ports result_out[4]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[4]]
set_property PACKAGE_PIN AK35 [get_ports result_out[5]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[5]]
set_property PACKAGE_PIN AL35 [get_ports result_out[6]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[6]]
set_property PACKAGE_PIN AJ31 [get_ports result_out[7]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[7]]
set_property PACKAGE_PIN AH34 [get_ports result_out[8]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[8]]
set_property PACKAGE_PIN AJ35 [get_ports result_out[9]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[9]]
set_property PACKAGE_PIN AM34 [get_ports result_out[10]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[10]]
set_property PACKAGE_PIN BB41 [get_ports result_out[11]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[11]]
set_property PACKAGE_PIN BA41 [get_ports result_out[12]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[12]]
set_property PACKAGE_PIN AL36 [get_ports result_out[13]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[13]]
set_property PACKAGE_PIN AY37 [get_ports result_out[14]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[14]]
set_property PACKAGE_PIN AV36 [get_ports result_out[15]]
set_property IOSTANDARD LVCMOS18 [get_ports result_out[15]]




## exp_rom ONLY
# set_property PACKAGE_PIN AR40 [get_ports td[0]]
# set_property IOSTANDARD LVCMOS18 [get_ports td[0]]
# set_property PACKAGE_PIN AU38 [get_ports td[1]]
# set_property IOSTANDARD LVCMOS18 [get_ports td[1]]
# set_property PACKAGE_PIN AP40 [get_ports td[2]]
# set_property IOSTANDARD LVCMOS18 [get_ports td[2]]
# set_property PACKAGE_PIN BB31 [get_ports td[3]]
# set_property IOSTANDARD LVCMOS18 [get_ports td[3]]
# set_property PACKAGE_PIN BA30 [get_ports td[4]]
# set_property IOSTANDARD LVCMOS18 [get_ports td[4]]
# set_property PACKAGE_PIN AT31 [get_ports td[5]]
# set_property IOSTANDARD LVCMOS18 [get_ports td[5]]