 # use constr file in the same directory #
set_property PACKAGE_PIN AK34 [get_ports usrclk_p]
set_property IOSTANDARD LVDS [get_ports usrclk_p]
set_property PACKAGE_PIN AL34 [get_ports usrclk_n]
set_property IOSTANDARD LVDS [get_ports usrclk_n]

set_property PACKAGE_PIN AU33 [get_ports rx_in]
set_property IOSTANDARD LVCMOS18 [get_ports rx_in]
set_property PACKAGE_PIN AU36 [get_ports tx_out]
set_property IOSTANDARD LVCMOS18 [get_ports tx_out]

set_property PACKAGE_PIN AU39 [get_ports fifo_full_led]
set_property IOSTANDARD LVCMOS18 [get_ports fifo_full_led]


set_property PACKAGE_PIN AV39 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports reset]

# to use UART project
set_property PACKAGE_PIN AK34 [get_ports usrclk_p]
set_property IOSTANDARD LVDS [get_ports usrclk_p]
set_property PACKAGE_PIN AL34 [get_ports usrclk_n]
set_property IOSTANDARD LVDS [get_ports usrclk_n]

set_property PACKAGE_PIN AU39 [get_ports led[7]]
set_property IOSTANDARD LVCMOS18 [get_ports led[7]]
set_property PACKAGE_PIN AP42 [get_ports led[6]]
set_property IOSTANDARD LVCMOS18 [get_ports led[6]]
set_property PACKAGE_PIN AP41 [get_ports led[5]]
set_property IOSTANDARD LVCMOS18 [get_ports led[5]]
set_property PACKAGE_PIN AR35 [get_ports led[4]]
set_property IOSTANDARD LVCMOS18 [get_ports led[4]]
set_property PACKAGE_PIN AT37 [get_ports led[3]]
set_property IOSTANDARD LVCMOS18 [get_ports led[3]]
set_property PACKAGE_PIN AR37 [get_ports led[2]]
set_property IOSTANDARD LVCMOS18 [get_ports led[2]]
set_property PACKAGE_PIN AN39 [get_ports led[1]]
set_property IOSTANDARD LVCMOS18 [get_ports led[1]]
set_property PACKAGE_PIN AM39 [get_ports led[0]]
set_property IOSTANDARD LVCMOS18 [get_ports led[0]]

set_property PACKAGE_PIN AU33 [get_ports rx_data_in]
set_property IOSTANDARD LVCMOS18 [get_ports rx_data_in]
set_property PACKAGE_PIN AU36 [get_ports tx_data_out]
set_property IOSTANDARD LVCMOS18 [get_ports tx_data_out]


set_property PACKAGE_PIN BB31 [get_ports slide_sw[7]]
set_property IOSTANDARD LVCMOS18 [get_ports slide_sw[7]]
set_property PACKAGE_PIN BA30 [get_ports slide_sw[6]]
set_property IOSTANDARD LVCMOS18 [get_ports slide_sw[6]]
set_property PACKAGE_PIN AY30 [get_ports slide_sw[5]]
set_property IOSTANDARD LVCMOS18 [get_ports slide_sw[5]]
set_property PACKAGE_PIN AW30 [get_ports slide_sw[4]]
set_property IOSTANDARD LVCMOS18 [get_ports slide_sw[4]]
set_property PACKAGE_PIN BA32 [get_ports slide_sw[3]]
set_property IOSTANDARD LVCMOS18 [get_ports slide_sw[3]]
set_property PACKAGE_PIN BA31 [get_ports slide_sw[2]]
set_property IOSTANDARD LVCMOS18 [get_ports slide_sw[2]]
set_property PACKAGE_PIN AY33 [get_ports slide_sw[1]]
set_property IOSTANDARD LVCMOS18 [get_ports slide_sw[1]]
set_property PACKAGE_PIN AV30 [get_ports slide_sw[0]]
set_property IOSTANDARD LVCMOS18 [get_ports slide_sw[0]]